### ISSUE TITLE
mention contact person in Slack message

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/ecosystem-ci#13]
## 🚀 Feature

Mention contact person in particular slack message

### Pitch

The user can safely ignore all that is not related to him...

### Alternatives

add in the receipt yaml contact with names and then add these people in message
```yaml
contact:
    slack:
      - Borda
    email: ...
```
add a command for parsing with arg `--channel slack`
